USERID_FOR_MASSLOOKER = [
"simowesta",
    "w0rla",
    "aqua.web",
    "precious.ideas.ever",
    "azecon",
    "taswikdotcom",
    "mofedoon",
    "arabsbusiness",
    "glorynaire",
    "coach_3ammar",
    "toop.quote",
    "taqif_nefsak",
    "millionairesarab",
    "arabic_billionaire",
    "tatwirdat",
    "mohamed.3_annouri",
    "learn_english_with_us2016",
    "zenglish_a",
    "maroc.motivation",
    "edlibrecom",
    "azizafkar_"
    ]

USERID_FOR_INSHACKLE = [
"chouftv_official",
    "hespress",
    "welovebuzzar",
    "kawtarbamo",
    "rajaabelmir",
    "reda_elwahabii",
    "omarbelmir",
    "adiltaouil",
    "meryemasouab",
    "manalbenchlikha",
    ]
